#! C:/Program Files (x86)/Python27
# -*- coding: utf-8 -*-
# Project       :计网大作业
# Module        :expression.py
# Description   :聊天界面
# Author        :Changsheng Zhang 
# Last edited   :2014/12/22 03:38

# Form implementation generated from reading ui file 'Emotion.ui'
#
# Created: Mon Dec 22 03:37:57 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(469, 371)
        self.gridLayoutWidget = QtGui.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 20, 371, 301))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton_23 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_23.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("expression/23.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_23.setIcon(icon)
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.gridLayout_2.addWidget(self.pushButton_23, 4, 4, 1, 1)
        self.pushButton_22 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_22.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("expression/22.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_22.setIcon(icon1)
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.gridLayout_2.addWidget(self.pushButton_22, 4, 3, 1, 1)
        self.pushButton_21 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_21.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("expression/21.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_21.setIcon(icon2)
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.gridLayout_2.addWidget(self.pushButton_21, 4, 2, 1, 1)
        self.pushButton_31 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_31.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("expression/31.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_31.setIcon(icon3)
        self.pushButton_31.setObjectName(_fromUtf8("pushButton_31"))
        self.gridLayout_2.addWidget(self.pushButton_31, 6, 0, 1, 1)
        self.pushButton_25 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_25.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("expression/25.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_25.setIcon(icon4)
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.gridLayout_2.addWidget(self.pushButton_25, 5, 0, 1, 1)
        self.pushButton_13 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_13.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("expression/13.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon5)
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.gridLayout_2.addWidget(self.pushButton_13, 3, 0, 1, 1)
        self.pushButton_26 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_26.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("expression/26.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_26.setIcon(icon6)
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.gridLayout_2.addWidget(self.pushButton_26, 5, 1, 1, 1)
        self.pushButton_28 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_28.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("expression/28.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_28.setIcon(icon7)
        self.pushButton_28.setObjectName(_fromUtf8("pushButton_28"))
        self.gridLayout_2.addWidget(self.pushButton_28, 5, 3, 1, 1)
        self.pushButton_12 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_12.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("expression/12.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon8)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.gridLayout_2.addWidget(self.pushButton_12, 2, 5, 1, 1)
        self.pushButton_09 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_09.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("expression/09.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_09.setIcon(icon9)
        self.pushButton_09.setObjectName(_fromUtf8("pushButton_09"))
        self.gridLayout_2.addWidget(self.pushButton_09, 2, 2, 1, 1)
        self.pushButton_27 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_27.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("expression/27.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_27.setIcon(icon10)
        self.pushButton_27.setObjectName(_fromUtf8("pushButton_27"))
        self.gridLayout_2.addWidget(self.pushButton_27, 5, 2, 1, 1)
        self.pushButton_08 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_08.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("expression/08.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_08.setIcon(icon11)
        self.pushButton_08.setObjectName(_fromUtf8("pushButton_08"))
        self.gridLayout_2.addWidget(self.pushButton_08, 2, 1, 1, 1)
        self.pushButton_14 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_14.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("expression/14.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon12)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.gridLayout_2.addWidget(self.pushButton_14, 3, 1, 1, 1)
        self.pushButton_18 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_18.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("expression/18.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_18.setIcon(icon13)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.gridLayout_2.addWidget(self.pushButton_18, 3, 5, 1, 1)
        self.pushButton_17 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_17.setText(_fromUtf8(""))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("expression/17.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_17.setIcon(icon14)
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.gridLayout_2.addWidget(self.pushButton_17, 3, 4, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_10.setText(_fromUtf8(""))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("expression/10.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon15)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_2.addWidget(self.pushButton_10, 2, 3, 1, 1)
        self.pushButton_20 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_20.setText(_fromUtf8(""))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("expression/20.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_20.setIcon(icon16)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.gridLayout_2.addWidget(self.pushButton_20, 4, 1, 1, 1)
        self.pushButton_19 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_19.setText(_fromUtf8(""))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("expression/19.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_19.setIcon(icon17)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.gridLayout_2.addWidget(self.pushButton_19, 4, 0, 1, 1)
        self.pushButton_02 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_02.setText(_fromUtf8(""))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8("expression/02.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_02.setIcon(icon18)
        self.pushButton_02.setObjectName(_fromUtf8("pushButton_02"))
        self.gridLayout_2.addWidget(self.pushButton_02, 1, 1, 1, 1)
        self.pushButton_03 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_03.setText(_fromUtf8(""))
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8("expression/03.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_03.setIcon(icon19)
        self.pushButton_03.setObjectName(_fromUtf8("pushButton_03"))
        self.gridLayout_2.addWidget(self.pushButton_03, 1, 2, 1, 1)
        self.pushButton_07 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_07.setText(_fromUtf8(""))
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8("expression/07.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_07.setIcon(icon20)
        self.pushButton_07.setObjectName(_fromUtf8("pushButton_07"))
        self.gridLayout_2.addWidget(self.pushButton_07, 2, 0, 1, 1)
        self.pushButton_06 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_06.setText(_fromUtf8(""))
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8("expression/06.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_06.setIcon(icon21)
        self.pushButton_06.setObjectName(_fromUtf8("pushButton_06"))
        self.gridLayout_2.addWidget(self.pushButton_06, 1, 5, 1, 1)
        self.pushButton_04 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_04.setText(_fromUtf8(""))
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8("expression/04.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_04.setIcon(icon22)
        self.pushButton_04.setObjectName(_fromUtf8("pushButton_04"))
        self.gridLayout_2.addWidget(self.pushButton_04, 1, 3, 1, 1)
        self.pushButton_05 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_05.setText(_fromUtf8(""))
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8("expression/05.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_05.setIcon(icon23)
        self.pushButton_05.setObjectName(_fromUtf8("pushButton_05"))
        self.gridLayout_2.addWidget(self.pushButton_05, 1, 4, 1, 1)
        self.pushButton_24 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_24.setText(_fromUtf8(""))
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8("expression/24.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_24.setIcon(icon24)
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.gridLayout_2.addWidget(self.pushButton_24, 4, 5, 1, 1)
        self.pushButton_15 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_15.setText(_fromUtf8(""))
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8("expression/15.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_15.setIcon(icon25)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.gridLayout_2.addWidget(self.pushButton_15, 3, 2, 1, 1)
        self.pushButton_11 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_11.setText(_fromUtf8(""))
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8("expression/11.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon26)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout_2.addWidget(self.pushButton_11, 2, 4, 1, 1)
        self.pushButton_16 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_16.setText(_fromUtf8(""))
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8("expression/16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_16.setIcon(icon27)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.gridLayout_2.addWidget(self.pushButton_16, 3, 3, 1, 1)
        self.pushButton_30 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_30.setText(_fromUtf8(""))
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8("expression/30.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_30.setIcon(icon28)
        self.pushButton_30.setObjectName(_fromUtf8("pushButton_30"))
        self.gridLayout_2.addWidget(self.pushButton_30, 5, 5, 1, 1)
        self.pushButton_32 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_32.setText(_fromUtf8(""))
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(_fromUtf8("expression/32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_32.setIcon(icon29)
        self.pushButton_32.setObjectName(_fromUtf8("pushButton_32"))
        self.gridLayout_2.addWidget(self.pushButton_32, 6, 1, 1, 1)
        self.pushButton_29 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_29.setText(_fromUtf8(""))
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(_fromUtf8("expression/29.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_29.setIcon(icon30)
        self.pushButton_29.setObjectName(_fromUtf8("pushButton_29"))
        self.gridLayout_2.addWidget(self.pushButton_29, 5, 4, 1, 1)
        self.pushButton_33 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_33.setText(_fromUtf8(""))
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(_fromUtf8("expression/33.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_33.setIcon(icon31)
        self.pushButton_33.setObjectName(_fromUtf8("pushButton_33"))
        self.gridLayout_2.addWidget(self.pushButton_33, 6, 2, 1, 1)
        self.pushButton_36 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_36.setText(_fromUtf8(""))
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(_fromUtf8("expression/36.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_36.setIcon(icon32)
        self.pushButton_36.setObjectName(_fromUtf8("pushButton_36"))
        self.gridLayout_2.addWidget(self.pushButton_36, 6, 5, 1, 1)
        self.pushButton_35 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_35.setText(_fromUtf8(""))
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(_fromUtf8("expression/35.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_35.setIcon(icon33)
        self.pushButton_35.setObjectName(_fromUtf8("pushButton_35"))
        self.gridLayout_2.addWidget(self.pushButton_35, 6, 4, 1, 1)
        self.pushButton_34 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_34.setText(_fromUtf8(""))
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(_fromUtf8("expression/34.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_34.setIcon(icon34)
        self.pushButton_34.setObjectName(_fromUtf8("pushButton_34"))
        self.gridLayout_2.addWidget(self.pushButton_34, 6, 3, 1, 1)
        self.pushButton_01 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_01.setText(_fromUtf8(""))
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(_fromUtf8("expression/01.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_01.setIcon(icon35)
        self.pushButton_01.setObjectName(_fromUtf8("pushButton_01"))
        self.gridLayout_2.addWidget(self.pushButton_01, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "选择表情", None))

